### ISSUE TITLE
To train autoencoders to classify fashion MNIST Data

### ISSUE THREAD

**Issue by Mohamed-Ayaan358** [acmpesuecc/code_snips#2]
This code aims to classify fashion MNIST data(This is used as an example).

Obviously can be altered for different data.

**Comment by Mohamed-Ayaan358** [comment]
@RakshithRAcharya,you gotta comment here

**Comment by RakshithRAcharya** [comment]
Sure......about what??

**Comment by Mohamed-Ayaan358** [comment]
Nothing needed ya to comment for me to assign 😂

**Comment by Mohamed-Ayaan358** [comment]
You can work on the PR now

**Comment by RakshithRAcharya** [comment]
Sure
