### ISSUE TITLE
A simple animation of a ball bouncing in a box using the visual aspect of vpython.

### ISSUE THREAD

**Issue by mukunddeepak** [acmpesuecc/code_snips#5]
A Simple Animation of a ball bouncing in a box meant to serve as self explanatory teaching code for people who have never used the visual library Vpython

**Comment by Smuzzy-waiii** [comment]
May i be assigned to this

**Comment by mukunddeepak** [comment]
All the very best!

**Comment by Omicron02** [comment]
Could i be assigned to this please
